version: '3.8'

services:
  db:
    image: postgres:16
    container_name: church_postgres
    restart: always
    user: "0:0"
    environment:
      POSTGRES_DB: ${DB_NAME:-church_db}
      POSTGRES_USER: ${DB_USER:-church_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-church_password}
      TZ: "Europe/Berlin"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5402:5432"
    


  # web:
  #   build: .
  #   container_name: church_django
  #   restart: always
  #   environment:
  #     - DEBUG=${DEBUG:-False}
  #     - SECRET_KEY=${SECRET_KEY}
  #     - DB_NAME=${DB_NAME:-church_db}
  #     - DB_USER=${DB_USER:-church_user}
  #     - DB_PASSWORD=${DB_PASSWORD:-church_password}
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
  #   volumes:
  #     - ./staticfiles:/app/staticfiles
  #     - ./media:/app/media
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: church_nginx
    restart: always
    user: "0:0"
    environment:
      - WEB_HOST=${WEB_HOST:-localhost}
      - DJANGO_HOST=${DJANGO_HOST:-host.docker.internal}
      - DJANGO_PORT=${DJANGO_PORT:-8000}
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    command: >
      /bin/sh -c "envsubst '$$WEB_HOST $$DJANGO_HOST $$DJANGO_PORT' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    depends_on:
      - web
